site_name: dianhsu's wiki
site_url: https://dianhsu.github.io/wiki/
nav:
  - 首页: index.md
  - 数学: 
    - 首页: math/index.md
  - 字符串: string/index.md
  - 游戏: game/index.md
  - 图论: graph/index.md
  - 计算几何: geometry/index.md
  - 数据结构: data_structure/index.md
  - 杂项: miscellaneous/index.md
theme: 
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - content.code.copy
    - toc.follow
  language: 'zh'
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: false
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - tables
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - css/extra.css 
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js


extra:
  search:
    language: 
      - 'jp'
      - 'en'